export const COUNTRIES = [
  { name: 'Australia', code: 'AU'},
  { name: 'New Zealand', code: 'NZ'},
  { name: 'United States', code: 'US'},
  { name: 'United Kingdom', code: 'GB'},
  { name: 'Ireland', code: 'IE'},
  { name: 'Russian Federation', code: 'RU'},
  { name: 'Japan', code: 'JP'},
  { name: 'Canada', code: 'CA'},
  { name: 'Sweden', code: 'SE'},
  { name: 'Ukraine', code: 'UA'},
  { name: 'Norway', code: 'NO'},
  { name: 'Korea, Republic of', code: 'KR'},
  { name: 'China', code: 'CN'},
  { name: 'Thailand', code: 'TH'},
  { name: 'Hungary', code: 'HU'},
  { name: 'Denmark', code: 'DK'},
  { name: 'Germany', code: 'DE'},
  { name: 'Netherlands', code: 'NL'},
  { name: 'Italy', code: 'IT'},
  { name: 'Taiwan, Province of China', code: 'TW'},
  { name: 'Spain', code: 'ES'},
  { name: 'Brazil', code: 'BR'},
  { name: 'France', code: 'FR'},
  { name: 'Serbia', code: 'RS'},
  { name: 'Israel', code: 'IL'},
  { name: 'Portugal', code: 'PT'},
  { name: 'Finland', code: 'FI'},
  { name: 'Belgium', code: 'BE'},
  { name: 'Poland', code: 'PL'},
  { name: 'Singapore', code: 'SG'},
  { name: 'Turkey', code: 'TR'},
];
